### ISSUE TITLE
Retirning to Data screen weird flashing

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#221]
Choppy transition when returning back to "Data" screen (looks like a flipbook) potentially due to text population ("All good!") or change of pineapple img

Bug. To be fixed by dev team.

**Comment by ricardobrg** [comment]
The same is happening with the choices screen, now with the test cards too. 
The cause is that we need to `await GoogleService.getConnectedUser()` to identify if the user is connected or not.
In the choices screen, it impacts the test cards too, because we need to await database access to check if the user already did the onboarding.

We should lift this state to the ApiUserService since it is inherent to the user state (user linked Gmail account? user did onboarding?). It can be accessed through Provider and will be consistent during the app lifecycle.
