### ISSUE TITLE
Setup Amplitude dashboards

### ISSUE THREAD

**Issue by ricardobrg** [tiki/app#528]

**Comment by NickkTMD** [comment]
Since we needed to switch to new Amplitude projects to flush out old, incorrect data, our amplitude dashboards need to be re-done.

We need a dashboard for viewing connected accounts and collected data points, our two KPI data types. 
We also need a chart to 

Acceptance Criteria
1. total accounts connected & target are on dashboard 
2. total data points connected & target are on dashboard
3. chart detailing types & amounts of signals created versus total emails fetched.

**Comment by NickkTMD** [comment]
![Image](https://user-images.githubusercontent.com/14880163/177395622-3956213a-d627-4c6a-8ce5-fbcd754f8d21.png)
![Image](https://user-images.githubusercontent.com/14880163/177395643-50038da0-b467-499e-946d-6ef54d833ff5.png)

dashboard link is in discord (should be kept private)

**Comment by ricardobrg** [comment]
@NickkTMD we need to update the connected accounts with this computation https://recommend.amplitude.com/org/116099/computations/xe9ipj9/
