### ISSUE TITLE
Email should submit on "enter" on login page

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#8]
When you click enter/done on the email form for login, the email should automatically submit. Users do not need to then additionally click the continue button. This will improve flow, particularly if the button is covered by the keyboard.

**Comment by annastoilova** [comment]
Let's talk about this. 

While it might look that it decreases the effort by saving 1 step, my worry is that this will increase the number of wrong emails entered, and then the user will have to keep going back.

For example, I almost always type my personal email on mobile as anna@annastoiova.com instead of anna@annastoilova.com and similar combinations, as my email is long.

**Comment by mike-audi** [comment]
okay, will not implement for now. closing
